name: base
channels:
  - defaults
dependencies:
  - _anaconda_depends=2025.12
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aiobotocore=2.25.0
  - aiodns=3.5.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.2
  - aioitertools=0.12.0
  - aiosignal=1.4.0
  - alabaster=0.7.16
  - alsa-lib=1.2.14
  - altair=5.5.0
  - anaconda-anon-usage=0.7.5
  - anaconda-auth=0.12.0
  - anaconda-catalogs=0.2.0
  - anaconda-cli-base=0.7.0
  - anaconda-client=1.14.0
  - anaconda-navigator=2.7.0
  - anaconda-project=0.11.1
  - annotated-types=0.6.0
  - anyio=4.10.0
  - aom=3.12.1
  - appdirs=1.4.4
  - archspec=0.2.5
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.4.0
  - arrow-cpp=21.0.0
  - astroid=3.3.11
  - astropy=7.1.1
  - astropy-iers-data=0.2025.11.10.0.38.31
  - asttokens=3.0.0
  - async-lru=2.0.5
  - asyncssh=2.21.1
  - atomicwrites=1.4.0
  - attrs=25.4.0
  - automat=24.8.1
  - autopep8=2.0.4
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.21.4
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.7
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.0
  - aws-sdk-cpp=1.11.638
  - babel=2.17.0
  - bcrypt=5.0.0
  - beautifulsoup4=4.13.5
  - binaryornot=0.4.4
  - black=25.9.0
  - blas=1.0
  - bleach=6.3.0
  - blinker=1.9.0
  - blosc=1.21.6
  - bokeh=3.8.0
  - boltons=25.0.0
  - botocore=1.40.46
  - bottleneck=1.4.2
  - brotlicffi=1.1.0.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - c-blosc2=2.17.1
  - ca-certificates=2025.11.4
  - cachetools=5.5.1
  - cairo=1.18.4
  - cattrs=25.3.0
  - certifi=2025.11.12
  - cffi=2.0.0
  - chardet=5.2.0
  - charset-normalizer=3.4.4
  - click=8.2.1
  - cloudpickle=3.1.1
  - colorcet=3.1.0
  - comm=0.2.3
  - conda=25.11.0
  - conda-anaconda-telemetry=0.3.0
  - conda-anaconda-tos=0.2.2
  - conda-build=25.11.1
  - conda-content-trust=0.2.0
  - conda-index=0.7.0
  - conda-libmamba-solver=25.11.0
  - conda-pack=0.8.1
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.12.0
  - conda-repo-cli=1.0.173
  - constantly=23.10.4
  - contourpy=1.3.3
  - cookiecutter=2.6.0
  - cpp-expected=1.1.0
  - cryptography=46.0.3
  - cssselect=1.2.0
  - curl=8.16.0
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dask=2025.11.0
  - dask-core=2025.11.0
  - datashader=0.18.2
  - dav1d=1.2.1
  - dbus=1.16.2
  - debugpy=1.8.16
  - decorator=5.2.1
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - dill=0.4.0
  - distributed=2025.11.0
  - distro=1.9.0
  - docstring-to-markdown=0.17
  - docutils=0.21.2
  - et_xmlfile=2.0.0
  - evalidate=2.0.3
  - executing=2.2.1
  - expat=2.7.3
  - filelock=3.20.0
  - flake8=7.1.1
  - flask=3.1.2
  - fmt=11.2.0
  - fontconfig=2.15.0
  - fonttools=4.60.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - frozendict=2.4.6
  - frozenlist=1.8.0
  - fsspec=2025.10.0
  - gettext=0.21.0
  - gflags=2.2.2
  - gitdb=4.0.12
  - gitpython=3.1.45
  - glib=2.84.4
  - glib-tools=2.84.4
  - glog=0.5.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - greenlet=3.2.4
  - gst-plugins-base=1.24.12
  - gstreamer=1.24.12
  - gstreamer-orc=0.4.41
  - h11=0.16.0
  - h5py=3.15.1
  - harfbuzz=10.2.0
  - hdf5=1.14.5
  - heapdict=1.0.1
  - holoviews=1.22.0
  - html5lib=1.1
  - httpcore=1.0.9
  - httpx=0.28.1
  - hvplot=0.12.1
  - hyperlink=21.0.0
  - icu=73.1
  - idna=3.11
  - imageio=2.37.2
  - imagesize=1.4.1
  - imbalanced-learn=0.14.0
  - importlib-metadata=8.7.0
  - incremental=24.7.2
  - inflection=0.5.1
  - iniconfig=2.1.0
  - intake=2.0.8
  - intel-openmp=2025.0.0
  - intervaltree=3.1.0
  - ipykernel=6.31.0
  - ipympl=0.9.7
  - ipython=9.7.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - isort=6.1.0
  - itemadapter=0.12.1
  - itemloaders=1.3.2
  - itsdangerous=2.2.0
  - jansson=2.14
  - jaraco.classes=3.4.0
  - jaraco.context=6.0.0
  - jaraco.functools=4.1.0
  - jedi=0.19.2
  - jeepney=0.7.1
  - jellyfish=1.2.1
  - jinja2=3.1.6
  - jmespath=1.0.1
  - joblib=1.5.2
  - jpeg=9f
  - jq=1.8.1
  - json5=0.12.1
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - jsonschema=4.25.0
  - jsonschema-specifications=2025.9.1
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.7
  - jupyterlab-variableinspector=3.2.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - jupyterlab_widgets=3.0.15
  - keyring=25.7.0
  - kiwisolver=1.4.9
  - lazy_loader=0.4
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20250127.0
  - libarchive=3.8.2
  - libavif=1.3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang13=20.1.8
  - libcups=2.4.2
  - libcurl=8.16.0
  - libdeflate=1.22
  - libdrm=2.4.124
  - libedit=3.1.20230828
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.84.4
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libgrpc=1.71.0
  - libiconv=1.16
  - libidn2=2.3.8
  - libkrb5=1.21.3
  - liblief=0.16.4
  - libllvm15=15.0.7
  - libllvm20=20.1.8
  - libmamba=2.3.2
  - libmambapy=2.3.2
  - libmpdec=4.0.0
  - libnghttp2=1.67.1
  - libogg=1.3.5
  - libopengl=1.7.0
  - libopenjpeg=2.5.4
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.6
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsodium=1.0.20
  - libsolv=0.7.30
  - libspatialindex=1.9.3
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libunistring=1.3
  - libuuid=1.41.5
  - libuv=1.48.0
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxkbfile=1.1.0
  - libxml2=2.13.9
  - libxslt=1.1.43
  - libzlib=1.3.1
  - linkify-it-py=2.0.3
  - llvmlite=0.45.1
  - lmdb=0.9.31
  - locket=1.0.0
  - lsprotocol=2025.0.0
  - lxml=5.3.0
  - lz4=4.4.5
  - lz4-c=1.9.4
  - lzo=2.10
  - markdown=3.8
  - markdown-it-py=2.2.0
  - markupsafe=3.0.2
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.2.1
  - mbedtls=3.5.1
  - mccabe=0.7.0
  - mdit-py-plugins=0.5.0
  - mdurl=0.1.2
  - menuinst=2.4.1
  - mesalib=25.1.5
  - mistune=3.1.2
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - more-itertools=10.8.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpi=1.0
  - mpi4py=4.0.3
  - mpich=4.3.2
  - mpmath=1.3.0
  - msgpack-python=1.1.1
  - multidict=6.7.0
  - multipledispatch=1.0.0
  - mypy=1.17.1
  - mypy_extensions=1.0.0
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - narwhals=2.7.0
  - navigator-updater=0.6.0
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.5
  - nlohmann_json=3.11.2
  - nltk=3.9.2
  - notebook=7.4.5
  - notebook-shim=0.2.4
  - nspr=4.37
  - nss=3.117
  - numba=0.62.1
  - numexpr=2.14.1
  - numpy=2.3.5
  - numpy-base=2.3.5
  - numpydoc=1.9.0
  - oniguruma=6.9.10
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openpyxl=3.1.5
  - openssl=3.0.18
  - orc=2.2.0
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.3
  - pandoc=3.8
  - pandocfilters=1.5.1
  - panel=1.8.3
  - param=2.3.0
  - parsel=1.10.0
  - parso=0.8.5
  - partd=1.4.2
  - patch=2.8
  - patchelf=0.17.2
  - pathspec=0.12.1
  - patsy=1.0.1
  - pcre2=10.46
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - pkce=1.0.3
  - pkginfo=1.12.0
  - platformdirs=4.5.0
  - plotly=6.3.0
  - pluggy=1.5.0
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - propcache=0.3.1
  - protego=0.4.0
  - protobuf=5.29.3
  - psutil=7.0.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-cpuinfo=9.0.0
  - py-lief=0.16.4
  - pyarrow=21.0.0
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.2
  - pybind11-abi=5
  - pycares=4.10.0
  - pycodestyle=2.12.1
  - pycosat=0.6.6
  - pycparser=2.23
  - pyct=0.6.0
  - pycurl=7.45.7
  - pydantic=2.12.4
  - pydantic-core=2.41.5
  - pydantic-settings=2.12.0
  - pydispatcher=2.0.7
  - pydocstyle=6.3.0
  - pyerfa=2.0.1.5
  - pyflakes=3.2.0
  - pygithub=2.8.1
  - pygments=2.19.2
  - pyjwt=2.10.1
  - pylint=3.3.8
  - pylint-venv=3.0.3
  - pyls-spyder=0.4.0
  - pynacl=1.6.0
  - pyodbc=5.3.0
  - pyopenssl=25.3.0
  - pyparsing=3.2.5
  - pyqt=5.15.11
  - pyqt5-sip=12.17.0
  - pyqtwebengine=5.15.11
  - pyside6=6.9.2
  - pysocks=1.7.1
  - pytables=3.10.2
  - pytest=8.4.2
  - python=3.13.9
  - python-dateutil=2.9.0post0
  - python-dotenv=1.1.0
  - python-fastjsonschema=2.21.2
  - python-json-logger=3.2.1
  - python-libarchive-c=5.1
  - python-lmdb=1.7.5
  - python-lsp-black=2.0.0
  - python-lsp-jsonrpc=1.1.2
  - python-lsp-ruff=2.3.0
  - python-lsp-server=1.13.1
  - python-slugify=8.0.4
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytokens=0.3.0
  - pytoolconfig=1.2.6
  - pytz=2025.2
  - pyuca=1.2
  - pyviz_comms=3.0.6
  - pywavelets=1.9.0
  - pyxdg=0.28
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qdarkstyle=3.2.3
  - qstylizer=0.2.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtawesome=1.4.0
  - qtbase=6.9.2
  - qtconsole=5.7.0
  - qtdeclarative=6.9.2
  - qtpy=2.4.3
  - qtshadertools=6.9.2
  - qtsvg=6.9.2
  - qttools=6.9.2
  - qtwebchannel=6.9.2
  - qtwebengine=6.9.2
  - qtwebsockets=6.9.2
  - queuelib=1.8.0
  - re2=2024.07.02
  - readchar=4.2.1
  - readline=8.3
  - referencing=0.37.0
  - regex=2025.9.1
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.5
  - requests-file=2.1.0
  - requests-toolbelt=1.0.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=14.2.0
  - roman-numerals-py=3.1.0
  - rope=1.14.0
  - rpds-py=0.28.0
  - rtree=1.4.1
  - ruamel.yaml=0.18.16
  - ruamel.yaml.clib=0.2.14
  - ruamel_yaml=0.17.21
  - ruff=0.12.0
  - s2n=1.5.14
  - s3fs=2025.10.0
  - scikit-image=0.25.2
  - scikit-learn=1.7.2
  - scipy=1.16.3
  - scrapy=2.13.3
  - seaborn=0.13.2
  - secretstorage=3.4.0
  - semver=3.0.4
  - send2trash=1.8.2
  - service_identity=24.2.0
  - setuptools=80.9.0
  - shellingham=1.5.4
  - simdjson=3.10.1
  - sip=6.12.0
  - six=1.17.0
  - smmap=4.0.0
  - snappy=1.2.1
  - sniffio=1.3.0
  - snowballstemmer=3.0.1
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sphinx=8.2.3
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=2.0.0
  - spirv-tools=2025.1
  - spyder=6.1.0
  - spyder-kernels=3.1.1
  - sqlalchemy=2.0.43
  - sqlite=3.51.0
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - streamlit=1.51.0
  - superqt=0.7.6
  - sympy=1.14.0
  - tabulate=0.9.0
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - tblib=3.1.0
  - tenacity=9.1.2
  - terminado=0.18.1
  - text-unidecode=1.3
  - textdistance=4.6.3
  - threadpoolctl=3.5.0
  - three-merge=0.1.1
  - tifffile=2025.10.4
  - tinycss2=1.4.0
  - tk=8.6.15
  - tldextract=5.1.2
  - toml=0.10.2
  - tomli=2.2.1
  - tomlkit=0.13.3
  - toolz=1.0.0
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - truststore=0.10.1
  - twisted=25.5.0
  - typer=0.17.4
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025b
  - uc-micro-py=1.0.3
  - ujson=5.11.0
  - unixodbc=2.3.14
  - urllib3=2.5.0
  - utf8proc=2.6.1
  - uvloop=0.22.1
  - w3lib=2.3.1
  - watchdog=6.0.0
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.1.3
  - whatthepatch=1.0.7
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - wrapt=1.17.0
  - wurlitzer=3.1.1
  - xarray=2025.10.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xyzservices=2025.4.0
  - xz=5.6.4
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - yapf=0.43.0
  - yarl=1.22.0
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.0.7
  - zope=1.0
  - zope.interface=8.0.1
  - zstandard=0.24.0
  - zstd=1.5.7
  - pip:
      - nvidia-cublas==13.0.0.19
      - nvidia-cuda-cupti==13.0.48
      - nvidia-cuda-nvrtc==13.0.48
      - nvidia-cuda-runtime==13.0.48
      - nvidia-cudnn-cu13==9.13.0.50
      - nvidia-cufft==12.0.0.15
      - nvidia-cufile==1.15.0.42
      - nvidia-curand==10.4.0.35
      - nvidia-cusolver==12.0.3.29
      - nvidia-cusparse==12.6.2.49
      - nvidia-cusparselt-cu13==0.8.0
      - nvidia-nccl-cu13==2.27.7
      - nvidia-nvjitlink==13.0.39
      - nvidia-nvshmem-cu13==3.3.24
      - nvidia-nvtx==13.0.39
      - torch==2.9.1+cu130
      - torchvision==0.24.1+cu130
      - triton==3.5.1
prefix: /home/xtjiang/anaconda3
